services:
  wordpress:
    image: wordpress:6.0.2-apache
    profiles:
      - wordpress-blog
    ports:
      - 80:80
    networks:
      - wordpress-network
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: thainm
      WORDPRESS_DB_PASSWORD: thainm@2001
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /opt/data/wordpress:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0.30 
    profiles:
      - wordpress-blog
    expose:
      - 3306
    networks:
      - wordpress-network
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: wordpress
      MYSQL_USER: thainm
      MYSQL_PASSWORD: thainm@2001
    volumes:
      - /opt/data/mysql:/var/lib/mysql
    restart: always

  nginx:
    image: nginx:1.22.0-alpine
    profiles:
      - wordpress-blog
    ports:
      - 8080:80
    networks:
      - wordpress-network
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

networks:
  wordpress-network:
    